version: '3'
services:
  database:
    image: postgres:latest
    environment: 
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=flaskapp1
    ports:
      - "5432:5432"
